language: php

php:
  - 5.3
  - 5.4

env:
  - MONGO_VERSION=1.3.6
  - MONGO_VERSION=1.2.11

services: mongodb

before_script:
  - printf "\n" | pecl install -f mongo-${MONGO_VERSION}
  - /bin/bash ./.travis.sh
  - phpenv rehash
  - composer --dev --prefer-source install

script: phpunit
